package konversisuhu;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtcel = new javax.swing.JTextField();
        txtfar = new javax.swing.JTextField();
        txtrea = new javax.swing.JTextField();
        txtkel = new javax.swing.JTextField();
        Bclear = new javax.swing.JButton();
        Bkelaur = new javax.swing.JButton();
        Bcelcius = new javax.swing.JButton();
        Bfahrenhait = new javax.swing.JButton();
        Breamur = new javax.swing.JButton();
        Bkelvin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KONVERSI SUHU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        txtcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelActionPerformed(evt);
            }
        });

        Bclear.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        Bclear.setText("Clear");
        Bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclearActionPerformed(evt);
            }
        });

        Bkelaur.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        Bkelaur.setText("Keluar");
        Bkelaur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkelaurActionPerformed(evt);
            }
        });

        Bcelcius.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        Bcelcius.setText("celcius");
        Bcelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcelciusActionPerformed(evt);
            }
        });

        Bfahrenhait.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        Bfahrenhait.setText("fahrenhait");
        Bfahrenhait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfahrenhaitActionPerformed(evt);
            }
        });

        Breamur.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        Breamur.setText("Reamur");
        Breamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreamurActionPerformed(evt);
            }
        });

        Bkelvin.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        Bkelvin.setText("kelvin");
        Bkelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkelvinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(Bclear)
                .addGap(143, 143, 143)
                .addComponent(Bkelaur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bcelcius, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtcel))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bfahrenhait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Breamur, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bkelvin, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(txtkel))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bfahrenhait)
                    .addComponent(Breamur)
                    .addComponent(Bcelcius)
                    .addComponent(Bkelvin))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bclear)
                    .addComponent(Bkelaur))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelActionPerformed

    private void BkelaurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkelaurActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BkelaurActionPerformed

    private void BclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclearActionPerformed
        // TODO add your handling code here:
        txtcel.setText("");
        txtfar.setText("");
        txtkel.setText("");
        txtrea.setText("");
        txtcel.requestFocus();
        txtfar.requestFocus();
        txtkel.requestFocus();
        txtrea.requestFocus();
        
    }//GEN-LAST:event_BclearActionPerformed

    private void BcelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcelciusActionPerformed
        // TODO add your handling code here:
        int celcius = Integer.parseInt(txtcel.getText());
      
      double far = (1.8*celcius)+32;
      double rea = (0.8*celcius);
      double kel = (celcius+273);
      
      txtfar.setText(String.valueOf(far));
      txtrea.setText(String.valueOf(rea));
      txtkel.setText(String.valueOf(kel));
      
      
      
     
    }//GEN-LAST:event_BcelciusActionPerformed

    private void BfahrenhaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfahrenhaitActionPerformed
        // TODO add your handling code here:
         int fahrenhait = Integer.parseInt(txtfar.getText());
      
      double cel = (fahrenhait-32)/1.8;
      double rea = (fahrenhait-32)/2.25;
      double kel = (fahrenhait+459)/1.8;
      
      txtcel.setText(String.valueOf(cel));
      txtrea.setText(String.valueOf(rea));
      txtkel.setText(String.valueOf(kel));
      
      
    }//GEN-LAST:event_BfahrenhaitActionPerformed

    private void BreamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreamurActionPerformed
        // TODO add your handling code here:
            int reamur = Integer.parseInt(txtrea.getText());
      
      double cel = (reamur/0.8);
      double far = (reamur*2.25)+491.67;
      double kel = (reamur/0.8)+273.15;
      
      txtcel.setText(String.valueOf(cel));
      txtfar.setText(String.valueOf(far));
      txtkel.setText(String.valueOf(kel));
      
      
    
    }//GEN-LAST:event_BreamurActionPerformed

    private void BkelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkelvinActionPerformed
        // TODO add your handling code here:
            int kelvin = Integer.parseInt(txtkel.getText());
      
      double cel = (kelvin-273.15);
      double far = (kelvin-273.15)*0.8;
      double rea = (kelvin*1.8-459.67);
      
      txtcel.setText(String.valueOf(cel));
      txtfar.setText(String.valueOf(far));
      txtrea.setText(String.valueOf(rea));
      
      
    }//GEN-LAST:event_BkelvinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcelcius;
    private javax.swing.JButton Bclear;
    private javax.swing.JButton Bfahrenhait;
    private javax.swing.JButton Bkelaur;
    private javax.swing.JButton Bkelvin;
    private javax.swing.JButton Breamur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcel;
    private javax.swing.JTextField txtfar;
    private javax.swing.JTextField txtkel;
    private javax.swing.JTextField txtrea;
    // End of variables declaration//GEN-END:variables
}
